name: first tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Chekout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Start Selenoid
        uses: Xotabu4/selenoid-github-action@v2
      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Publish test report
           uses: peaceiris/actions-gh-pages@v3
           if: always()
          with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_branch: gh-pages
              publish_dir: allure-history