name: first tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Chekout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Start Selenoid
        uses: Xotabu4/selenoid-github-action@v2
      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub